### PR TITLE
 Addresses issue #25 by making data processing less RAM intensive

### LINKED ISSUE #25: No updates
Hola,

Estoy usando su pagina y en especifico los updates que se publican cada dia de datos_abiertos/series_de_tiempo/nuevos/covid19_mex_*.csv. Es muy util y les agradezco mucho su trabajo muy importante.

Me parece que desde unos dias ya no hay actualización de estos datos. Hay un problema? Puedo ayudar a algo? Se un poco de python y podria correr un script cada dia para generar los datos si es necesario.

Gracias por su trabajo,

Saludos cordiales, cuidense mucho.

Ch. Morisset

### PR DESCRIPTION
**Pull request by blas-ko**
Edited process_datos_abiertos.py to read the data in chunks. 

We shouldn't have processing problems anymore. 

If this works, maybe we can close #25.

### CODE REVIEW

**Comment by rodrigolece** [comment]
The commits successfully update the time-series. Merging into the main branch.

**Comment by Morisset** [comment]
Great job! Thanks a lot!!!

**Comment by rodrigolece** [comment]
I just need one more commit in order to update the pyramids and I'm working on it. I'll update the time series next.

**Comment by blas-ko** [comment]
Many thanks, @Morisset :)

**Pull request merged**
